### ISSUE TITLE
minot typo in your ready

### ISSUE THREAD

**Issue by abitofalchemy** [nesquena/wikipedia_search#1]
you have 6 and 11 swapped where you refer to the word **elephant** as an example, appearing a total of  11 times and 6 times in the first document should be the correct wording. HTH

**Comment by nesquena** [comment]
Wow, I didn't think anyone ever looked at this repo let alone caught an error in the readme. Open source never ceases to amaze me. Thanks!

**Comment by nesquena** [comment]
2f6722edcf2880d7c33992ce55eb1fc811361fd9
